language: ruby
rvm:
  - 2.3.0
  - 2.2.3
  - 2.1.6
  - 1.9.3
  - rbx
  - jruby-19mode # JRuby in 1.9 mode

matrix:
  allow_failures:
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: rbx
    - rvm: 1.9.3
    - rvm: 2.1.6

services:
  - couchdb

script: bundle exec rake test_ragios
