apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
  namespace: ragios
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chrome
    spec:
      containers:
      - env:
        - name: HUB_HOST
          value: hub
        image: selenium/node-chrome:3.8.1-erbium
        name: chrome
        resources: {}
        volumeMounts:
        - mountPath: /dev/shm
          name: chrome-claim0
      restartPolicy: Always
      volumes:
      - name: chrome-claim0
        persistentVolumeClaim:
          claimName: chrome-claim0
status: {}
