apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
  namespace: ragios
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chrome
    spec:
      containers:
      - env:
        image: selenium/node-chrome:3.8.1-erbium
        name: chrome
        resources: {}
      restartPolicy: Always
status: {}
