apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
  namespace: ragios
spec:
  serviceName: couchdb
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
      - image: apache/couchdb:1.7.1
        name: couchdb
        ports:
        - containerPort: 5984
        volumeMounts:
        - name: couchdb-data
          mountPath: /volumes/couchdb/data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: couchdb-data
      labels:
        io.kompose.service: couchdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
