apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: firefox
  name: firefox
  namespace: ragios
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: firefox
    spec:
      containers:
      - env:
        - name: HUB_HOST
          value: hub
        image: selenium/node-firefox:3.8.1-erbium
        livenessProbe:
          exec:
            command:
            - wget
            - --spider
            - http://localhost:5555
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        name: firefox
        resources: {}
        volumeMounts:
        - mountPath: /dev/shm
          name: firefox-claim0
      restartPolicy: Always
      volumes:
      - name: firefox-claim0
        persistentVolumeClaim:
          claimName: firefox-claim0
status: {}
