apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hub
  name: hub
  namespace: ragios
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hub
    spec:
      containers:
      - env:
        - name: GRID_BROWSER_TIMEOUT
          value: "60"
        image: selenium/hub:3.8.1-erbium
        livenessProbe:
          exec:
            command:
            - wget
            - --spider
            - http://localhost:4444/grid/api/proxy
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        name: hub
        resources: {}
      restartPolicy: Always
status: {}
