apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
    app: web
  name: web
  namespace: ragios
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
        app: web
    spec:
      containers:
      - command:
        - bundle
        - exec
        - pumactl
        - -F
        - server.rb
        - start
        env:
        - name: HUB_HOST
          value: hub
        - name: HUB_PORT
          value: "4444"
        - name: RAGIOS_ENV
          value: production
        - name: RAGIOS_EVENTS_RECEIVER_ADDRESS
          value: events
        - name: RAGIOS_LOG_LEVEL
          value: info
        - name: RAGIOS_RECURRING_JOBS_RECEIVER_ADDRESS
          value: recurring-jobs
        - name: RAGIOS_WEB_SERVER_ADDRESS
          value: tcp://0.0.0.0:5041
        - name: RAGIOS_WEB_SERVER_ENV
          value: production
        - name: RAGIOS_AUTHENTICATION
          value: 'true'
        - name: SES_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ses-aws-secret
              key: ses_aws_access_key_id
        - name: SES_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ses-aws-secret
              key: ses_aws_secret_access_key
        - name: AWS_SES_SEND_FROM
          valueFrom:
            configMapKeyRef:
              name: ses-aws-config
              key: aws_ses_send_from
        - name: AWS_SES_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: ses-aws-config
              key: aws_ses_endpoint
        - name: RAGIOS_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: ragios-secret
              key: username
        - name: RAGIOS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ragios-secret
              key: password
        - name: COUCHDB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        image: obiora/maestro:v0.2.0
        name: web
        ports:
        - containerPort: 5041
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
