apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: workers
  name: workers
  namespace: ragios
spec:
  replicas: 4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: workers
    spec:
      containers:
      - command:
        - bundle
        - exec
        - ruby
        - bin/workers_ctl.rb
        - run
        env:
        - name: HUB_HOST
          value: hub
        - name: HUB_PORT
          value: "4444"
        - name: RAGIOS_ENV
          value: production
        - name: RAGIOS_EVENTS_RECEIVER_ADDRESS
          value: events
        - name: RAGIOS_LOG_LEVEL
          value: info
        - name: RAGIOS_NOTIFICATIONS_RECEIVER_ADDRESS
          value: notifications
        - name: RAGIOS_RECURRING_JOBS_RECEIVER_ADDRESS
          value: recurring-jobs
        - name: RAGIOS_WORKERS_PUSHER_ADDRESS
          value: recurring-jobs
        - name: SES_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ses-aws-secret
              key: ses_aws_access_key_id
        - name: SES_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ses-aws-secret
              key: ses_aws_secret_access_key
        - name: AWS_SES_SEND_FROM
          valueFrom:
            configMapKeyRef:
              name: ses-aws-config
              key: aws_ses_send_from
        - name: AWS_SES_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: ses-aws-config
              key: aws_ses_endpoint
        - name: COUCHDB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: username
        - name: COUCHDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: password
        - name: S3_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-aws-secret
              key: s3_aws_access_key_id
        - name: S3_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-aws-secret
              key: s3_aws_secret_access_key
        - name: RAGIOS_HERCULES_S3_DIR
          valueFrom:
            configMapKeyRef:
              name: s3-aws-config
              key: ragios_hercules_s3_dir
        - name: RAGIOS_HERCULES_ENABLE_SCREENSHOTS
          valueFrom:
            configMapKeyRef:
              name: s3-aws-config
              key: ragios_hercules_enable_screenshots
        image: obiora/maestro:v0.2.0
        name: workers
        ports:
        - containerPort: 5043
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
