apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chrome
  namespace: ragios
spec:
  template:
    spec:
      containers:
      - resources:
          limits:
            memory: 600Mi
          requests:
            memory: 200Mi
        name: chrome
