apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: firefox
  namespace: ragios
spec:
  template:
    spec:
      containers:
      - resources:
          limits:
            memory: 600Mi
            cpu: 100m
          requests:
            cpu: 50m
            memory: 200Mi
        name: firefox
